### ISSUE TITLE
Parcel output is difficult to read.

### ISSUE THREAD

**Issue by BedfordWest** [LabAdvComp/parcel#46]
In general, when downloading multiple files it is often difficult to see what is going on, especially if multiple files finish in quick succession or error messages/notifications are received. Recommend adding line breaks or other ways to "break up" the each file status to improve readability.

**Comment by millerjs** [comment]
Added color when supported and file summary after download process completes.  @BedfordWest if this is satisfactory, feel free to close the issue, if not, let me know what further features it needs for readability.

**Comment by BedfordWest** [comment]
Output looks good now! Thanks!
